{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  AGENT_API_TOKEN: {{ .Values.agentToken | default (randAlphaNum 32) | quote }}
  {{- if .Values.paytm.keySecret }}
  PAYTM_KEY_SECRET: {{ .Values.paytm.keySecret | quote }}
  {{- end }}
  {{- if .Values.paytm.webhookSecret }}
  PAYTM_WEBHOOK_SECRET: {{ .Values.paytm.webhookSecret | quote }}
  {{- end }}
{{- end }}
